version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate

    - save_cache:
        paths:
        - ./venv

    - run:
        name: run tests
        command: |
          . venv/bin/activate
          python basic.py test

    - store_artifacts:
        path: test-reports
        destination: test-reports

workflows:
  version: 2
  workflow:
    jobs:
    - build