version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-

    - run:
        name: install dependencies
        command: |
            sudo pip3 install -r requirements.txt

    - run:
        name: run tests
        command: |
            py.test

    - store_artifacts:
        path: test-reports
        destination: test-reports

workflows:
  version: 2
  workflow:
    jobs:
    - build